version: "3.7"

volumes:
  stay_database:

networks:
  stay:

services:
  app:
    container_name: stay_app
    build:
      context: ./docker
      dockerfile: App.DockerFile
    ports:
      - "9090:80"
    volumes:
      - "./:/var/www/stay"
      - "./docker/stay.conf:/etc/apache2/sites-available/000-default.conf"
      - "./docker/php.ini:/usr/local/etc/php/php.ini"
    networks:
      - stay
  db:
    image: mariadb:10.1
    container_name: stay_db
    ports:
      - "3333:3306"
    volumes:
      - "stay_database:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: stay
    networks:
      - stay
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: stay_phpmyadmin
    ports:
      - "9091:80"
    volumes:
      - "./docker/phpmyadmin.ini:/usr/local/etc/php/php.ini"
    environment:
      PMA_ARBRITARY: 1
      PMA_HOST: db
    networks:
      - stay
